### ISSUE TITLE
The file '' seems to be corrupt

### ISSUE THREAD

**Issue by rriveronb** [Sicos1977/OfficeConverter#7]
Hello I'm having this issue and I can't find a way to go around it.

The file 'OrderSummary.docx' seems to be corrupt, error: Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/92946952/138332660-e1e4255c-6844-41b1-b456-e5dc207972a1.png)

I have Office Installed and activated and the library works just fine on my development environment. The issue is just after deploy.

I give permissions to the folder, I'm able to open the document on Word and manually convert.

Do you have any ideas?

**Comment by Sicos1977** [comment]
What version of office did you install? And under what account is the app running?

**Comment by rriveronb** [comment]
I have Office365 running and on my last test I make the ApplicationPool to run under one of my administrators account
Thanks..

**Comment by cesardt** [comment]
Hi, I saw this issue was closed. Was a solution ever found? I'm having the same issue and have the same setup (Word 365 and ApplicationPool run under Administrator account).

**Comment by Sicos1977** [comment]
I had the same issue with Office 365 and switched back to Office 2016  because Office 2019 did also not work for some strange reason. I never reserved the time to figure out why my tool is not working with 2019 or 365 because using Office on a server is not supported by Microsoft and everything that I needed also worked fine with 2016.

I'm convinced that it should work but as you can see in the code I have to do some weird tweaks to make everything work. I guess something simular has to be done for 2019 and 365... but again never reserved the time for that because this probably is going to be a trail and error process with tools like processmon sysinternals to figure out why it does not work.

**Comment by cesardt** [comment]
Thank you for answering! Too bad that it breaks with new Office versions.
